server:
  port: 8081
  
spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5433/omninotify
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:default}
  auth-token: ${TWILIO_AUTH_TOKEN:default}
  from-number: ${TWILIO_FROM_NUMBER:default}

