server:
  port: 8082
  
spring:
  profiles:
    include: secrets
  application:
    name: subscription-service
  datasource:
    url: jdbc:postgresql://localhost:5433/omninotify
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

razorpay:
  key-id: ${RAZORPAY_KEY_ID:default}
  key-secret: ${RAZORPAY_KEY_SECRET:default}
